name: DÃ©ploiement de Nikola en GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  nikola_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build and Deploy Nikola
        uses: getnikola/nikola-action@v2
        env:
          GIT_CONFIG_COUNT: 1
          GIT_CONFIG_KEY_0: safe.directory
          GIT_CONFIG_VALUE_0: /github/workspace
        with:
          args: github_deploy
